env:
  browser: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules: {
  "no-console":["error", {
    "allow":["warn", "error", "info"]
  }]
}
